# Generated by Django 3.1.3 on 2020-12-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('shortDescription', models.CharField(max_length=255, null=True)),
                ('longDescription', models.CharField(max_length=2088, null=True)),
                ('coverImg', models.CharField(max_length=2083, null=True)),
                ('img1Url', models.CharField(max_length=2083, null=True)),
                ('img2Url', models.CharField(max_length=2083, null=True)),
                ('img3Url', models.CharField(max_length=2083, null=True)),
                ('img4Url', models.CharField(max_length=2083, null=True)),
                ('img5Url', models.CharField(max_length=2083, null=True)),
                ('img6Url', models.CharField(max_length=2083, null=True)),
                ('youtubeUrl', models.CharField(max_length=2083, null=True)),
            ],
        ),
    ]
