# Generated by Django 3.1.3 on 2020-12-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_games_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
