# Generated by Django 3.1.3 on 2020-12-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20201204_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='img4Url',
        ),
        migrations.RemoveField(
            model_name='games',
            name='img5Url',
        ),
        migrations.RemoveField(
            model_name='games',
            name='img6Url',
        ),
        migrations.AddField(
            model_name='games',
            name='console',
            field=models.CharField(choices=[('ps3', '1'), ('ps4', '2'), ('pc', '3'), ('Xbox', '4')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
