# Generated by Django 3.1.3 on 2020-12-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20201211_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='console',
            field=models.CharField(choices=[('ps3', 'ps3'), ('ps4', 'ps4'), ('pc', 'pc'), ('Xbox', 'Xbox')], max_length=5),
        ),
    ]
